config/routes.rb
Rails.application.routes.draw do

	root to: 'pages#top'

	# pagesコントローラー
  get 'home/about' => 'pages#about', as: 'about'
  get 'home'			 => 'pages#top',	 as: 'top'

  # deviseコントローラー
  devise_for :users

  #booksコントローラー
  resources :books do
    # bookに関連づいたfavorites
    resource :favorites, only: [:create, :destroy]
  end

  #usersコントローラー
  resources :users, only: [:show, :index, :edit, :update] do
    # userに関連づいたfavorites
    resources :favorites, only: [:index]
    # 相手userとのダイレクトメッセージ
    resources :direct_messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true

	
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy

	has_many :favorited, through: :favorites, source: :user

	validates :body, presence: true, length: {maximum: 200}
	validates :title, presence: true

		# ログインユーザーが投稿いいねしているかを確認する
		def has_favorite(user_id)
			favorites.find_by(user_id: user_id)
		end
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
	belongs_to :user
	belongs_to :to_user, class_name: "User"
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image

  # 複数の投稿を持つ
  has_many :books, dependent: :destroy
  # 複数のいいねを持つ
  has_many :favorites, dependent: :destroy
  # 複数のダイレクトメッセージを持つ
  has_many :direct_messages, dependent: :destroy

  # userがいいねしたbookを取得
  has_many :favorite_books, through: :favorites, source: :book

  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
  protected
	  def configure_permitted_parameters
      # 新規登録に使用するカラム
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
      # ログインに使用するカラム
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	  end


	  # サインイン後のリダイレクト先をマイページへ
	  def after_sign_in_path_for(resource)
	  	flash[:notice] = "ログインに成功しました"
    	user_path(current_user.id)
  	end

  	# サインアウト後のリダイレクト先をトップページへ
  	def after_sign_out_path_for(resource)
	  	flash[:alert] = "ログアウトしました"
    	top_path
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :only_made_user, only: [:edit, :destroy, :update]

  def index
  	@books = Book.all
  	@book = Book.new
    @user = User.find(current_user.id)
  end

  def create
  	@book = current_user.books.new(book_params)
    if @book.save
      flash[:book_create] = "Book was successfully created."
    	redirect_to books_path
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render 'index'
    end
  end

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    flash[:book_update] = "Book was successfully updated."
    redirect_to book_path
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:book_destroy] = "Book was successfully destroy"
    redirect_to books_path
  end


  private

  	def book_params
  		params.require(:book).permit(:title, :body, :user_id)
  	end

    # 投稿ユーザー以外に使用制限
    def only_made_user
      book = Book.find(params[:id])
      unless book.user == current_user
        flash[:alert] = "編集権限がありません"
        redirect_to user_path(current_user.id)
      end
    end


end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController

	def index
		# 自分とメッセージ交換を制限
		if @user == current_user
			redirect_to user_path(current_user.id)
		end

		@user = User.find(params[:user_id])
		@me = current_user
		@message = DirectMessage.new
		# 相手が贈ったものを追加, 自分が贈ったものを追加
		@direct_messages = DirectMessage.where("(user_id = ?) OR (to_user_id = ?)",current_user, current_user)
	end

	def create
		user = User.find(params[:user_id])
		direct_message = current_user.direct_messages.new(direct_message_params)
		direct_message.to_user_id = user.id
		direct_message.save
		redirect_to user_direct_messages_path(user_id: user.id)
	end

	private

		def direct_message_params
			params.require(:direct_message).permit(:direct_message)
		end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :call_models, only: [:create, :destroy]

	def create
		@favorite = Favorite.create(user_id: current_user.id, book_id: params[:book_id])
	end

	def destroy
		@favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
		@favorite.destroy
	end

	def index
		@user = User.find(params[:user_id])
		@favorite_books = @user.favorite_books
		@book = Book.new
	end

	private

		def call_models
			@book = Book.find(params[:book_id])
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# ユーザー認証を設けないページ

  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :protect_pages, only: [:edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books.all
  	@book = Book.new
  end

  def index
  	@user = User.find(current_user.id)
  	@users = User.all
  	@book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:user_update] = "User was successfully updated."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  	def books_params
  		params.require(:book).permit(:title, :body, :user_id)
  	end

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    # 自分以外のプロフィール編集を制限
    def protect_pages
      user = User.find(params[:id])
      unless user == current_user
        flash[:alert] = "編集権限がありません"
        redirect_to user_path(current_user.id)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# ユーザーのプロフィール画像を表示するメソッド(クラスの指定も可能)
	def user_image_tag(user, width, height, *classes)
		if user.profile_image_id
			attachment_image_tag(user, :profile_image, :fill, width, height, format: 'jpg', class: classes )
		else
			image_tag('img/no_image.jpg', class: classes, style: "width: #{width}px; height: #{height}px;")
		end
	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/direct_messages_helper.rb
module DirectMessagesHelper
		# 送り主によって配置を変更
	def change_pull_class(direct_message)
		if direct_message.user == current_user
			class_name = "pull-left"
			class_name
		else
			class_name = "pull-right"
			class_name
		end
	end
end

app/helpers/favorites_helper.rb
module FavoritesHelper


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book-alert-msg.html.erb
<% if flash[:book_create] %>
	<div class="alert alert-success">
		<%= flash[:book_create] %>
	</div>

<% elsif flash[:book_update] %>
	<div class="alert alert-info">
		<%= flash[:book_update] %>
	</div>

<% elsif flash[:book_destroy] %>
	<div class="alert alert-danger">
		<%= flash[:book_destroy] %>
	</div>
<% end %>

app/views/books/_book-form.html.erb
<!-- エラーメッセージの表示 -->
<%= render 'pages/erorr-messages', object: book %>

<%= form_for(book) do |f| %>

	<div class="form-group">
		<p>Title</p>
		<%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
	</div>

	<div class="form-group">
		<p>Body</p>
		<%= f.text_area :body, class: "form-control", placeholder: "本文(200文字まで)"  %>
	</div>

		<%= f.submit "#{btn_name}", class: "btn btn-primary btn-block" %>

<% end %>

app/views/books/_book-list.html.erb
<h1><strong>Books</strong></h1>
<!-- フラッフメッセージ -->
<%= render 'books/book-alert-msg' %>

<!-- 投稿一覧 -->
<table class="table table-hover">
	<thead>
		<tr>
			<th><strong>User Image</strong></th>
			<th><strong>Title</strong></th>
			<th><strong>Opinion</strong></th>
		</tr>
	</thead>
	<% books.each do |book| %>
	<tr>
		<td>
			<!-- 画像を押すとユーザー画面へ -->
			<%= link_to user_path(book.user.id) do %>
				<%= user_image_tag(book.user, 60, 60, "img-circle pull-left") %>
			<% end %>
		</td>
		<td><%= book.title %></td>
		<td><%= book.body %></td>

		<!-- イイネボタン -->
		<td>
		<div id= <%= "fav-#{book.id}" %>
			<%= render 'favorites/favorite-btn', book: book %>
			</div>
		</td>

		<td class="text-center">
			<div class="btn-group">
				<!-- 詳細ページへ -->
					<%= link_to "Show", book_path(book), class: "btn btn-info" %>

				<!-- 投稿者のみに制限 -->
				<% if book.user == current_user %>
					<!-- 編集ページへ -->
						<%= link_to "Edit", edit_book_path(book), class: "btn btn-success" %>

					<!-- 投稿削除 -->
						<%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger" %>
				<% end %>
			</div>
		<td>
	</tr>
	<% end %>
</table>

app/views/books/_new-book-form.html.erb
<h4 class="new-book-headline">New book</h4>
<%= form_for(book) do |f| %>

	<div class="form-group">
		<p>Title</p>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<p>Body</p>
		<%= f.text_area :body, class: "form-control"  %>
	</div>

		<%= f.submit "#{btn_name}", class: "btn btn-primary btn-block" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1><strong>Editing Book</strong></h1>
		

		<!-- 編集フォームの表示 -->
		<%= render 'books/book-form', book: @book,btn_name: "Update Book" %>

		<div>
			<%= link_to "Show", book_path(@book), class: "book-links" %>
			 | 
			 <%= link_to "Back", books_path, class: "book-links" %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<!-- 投稿削除後のみ表示 -->
<p class="destroyed-text">
	<%= flash[:notice] %>
</p>

<div class="row">
	<div class="col-md-3">
		<!-- ユーザー情報 -->
		<%= render 'users/user-info', user: @user %>
		<!-- 新規投稿フォーム -->
		<h4 class="new-book-headline">New book</h4>
		<%= render 'books/book-form', book: @book, btn_name: "Create Book" %>
	</div>

	<div class="col-md-9">
		<!-- 投稿一覧 -->
		<%= render 'books/book-list', books: @books %>
	</div>
</div>

app/views/books/show.html.erb
<!-- ユーザー情報を表示 -->
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'books/book-alert-msg' %>
	</div>
	<div class="col-md-6 col-md-offset-3 show-box">
		<div class="row show-book-user">
				<%= user_image_tag(@user, 100, 100, "col-md-3 img-circle") %>
				<h2 class="col-md-offset-2 col-md-7 show-user-name"> <%= @user.name %> </h2>
		</div>

		<!-- 投稿詳細情報を表示 -->
		<div>
			<div class="row show-title">
				<p class="col-md-3">Title</p>
				<p class="col-md-8"><%= @book.title %></p>
			</div>
			<div class="row show-opinion">
				<p class="col-md-3">Opinion</p>
				<p class="col-md-8"><%= @book.body %></p>
			</div>
		</div>
		<!-- ボタンの表示 -->
		<div class="row show-book-btn">
			<div class="btn-group col-md-offset-7 ">

				<!-- 投稿者のみに制限 -->
				<% if @book.user == current_user %>
					<!-- 編集ページへ -->
						<%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>

					<!-- 投稿削除 -->
						<%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" area-hiden="true"></span>Bookers   !!</h1>

	<div class="top-text-box">
		<p>
			In <span class="glyphicon glyphicon-book" area-hiden="true"><strong>Bookers</strong></span>,<br>
			you can share and exchange your opinions , inpressions , and emotions
			about varioius books!
		</p>
		<!-- ボタンのグループ -->
		<div class="raw">
			<div class="col-md-10 col-md-offset-1 ">
				<%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block top-btn" %>
				<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block top-btn" %>
			</div>
		</div>
	</div>
		</div>
	</div>
</div>

app/views/direct_messages/_message_form.html.erb
<!-- エラーメッセージの表示 -->
<%= render 'pages/erorr-messages', object: message %>

<%= form_for [user, message] do |f| %>

	<div class="form-group">
		<%= f.text_area :direct_message, rows: "5", class: "form-control", placeholder: "メッセージをここに！" %>
	</div>

		<%= f.submit "send message!", class: "btn btn-primary btn-block" %>

<% end %>

app/views/direct_messages/_message_list.html.erb
<div class="message-list-box">
	<% direct_messages.each do |direct_message| %>
		<div class=" clearfix" style="width: 100%;">
			<div class="message-list <%= change_pull_class(direct_message) %>">
					<%= direct_message.direct_message %>
			</div>
		</div>
	<% end %>
</div>

app/views/direct_messages/index.html.erb
<div class="row">
	<div class="col-md-3">
		<!-- ユーザー情報 -->
		<%= render 'users/user-info', user: @user %>
		<!-- 新規投稿フォーム -->
		<h4 class="new-book-headline">Direct Message</h4>
		<%= render 'direct_messages/message_form', message: @message, user: @user %>
	</div>

	<div class="col-md-5 col-md-offset-2">
	<%= render 'direct_messages/message_list', direct_messages: @direct_messages %>
	</div>
</div>

app/views/favorites/_favorite-btn.html.erb
<!-- イイネボタン -->

<!-- ログインしていないユーザーにいいねの制限 -->
<% if user_signed_in? %>
	<!-- ログインユーザーが投稿にイイねしていない場合	 -->
	<% if book.has_favorite(current_user.id) %>
    <%= button_to book_favorites_path(book_id: book.id), method: :delete, class: "btn btn-danger", remote: true do %>
					<span>いいね!</span>
					<span><%= book.favorites.count %></span>
    <% end %>

  <!-- イイねしている場合 -->
	<% else %>
		<%= button_to book_favorites_path(book.id), method: :post, class: "btn btn-primary", remote: true do  %>
			<span>いいね!</span>
			<span><%=book.favorites.count %></span>
		<% end %>
	<% end %>

<% else %>
			<span>いいね!</span>
			<span><%=book.favorites.count %></span>
<% end %>

app/views/favorites/create.js.erb
$("<%= "#fav-#{@book.id}" %>").html("<%= j(render partial: 'favorite-btn', locals: { book: @book}) %>");

app/views/favorites/destroy.js.erb
$("<%= "#fav-#{@book.id}" %>").html("<%= j(render partial: 'favorite-btn', locals: { book: @book }) %>");

app/views/favorites/index.html.erb
<div class="row">
	<div class="col-md-3">
		<!-- ユーザー情報 -->
		<%= render 'users/user-info', user: @user %>
		<!-- 新規投稿フォーム -->
		<h4 class="new-book-headline">New book</h4>
		<%= render 'books/book-form', book: @book, btn_name: "Create Book" %>
	</div>

	<div class="col-md-9">
		<!-- いいねしている投稿一覧 -->
		<%= render 'books/book-list', books: @favorite_books %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<p class="pull-right">CopyRight Infratop.inc</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top container-fluid">
	<div class="container">

		<!-- ロゴの表示 -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand logo-text" href="#">
				<span class="glyphicon glyphicon-book" area-hiden="true">Bookers</span>
			</a>
		</div>

		<!-- ナビバーを表示 -->
		<div class="collapse navbar-collapse" id="navbarEexample7">
			<ul class="nav navbar-nav navbar-right">

			<!-- ログイン済み表示 -->
			<% if user_signed_in? %>
				<li>
					<%= link_to " Home", user_path(current_user), class: "glyphicon glyphicon-home", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Users", users_path, class: "glyphicon glyphicon-link", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Books", books_path, class: "glyphicon glyphicon-book", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Favorite", user_favorites_path(current_user), class: "glyphicon glyphicon-star", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Log out", destroy_user_session_path,method: :delete, class: "glyphicon glyphicon-log-in", "aria-hidden" => true %>
				</li>

			<!-- 未ログイン表示 -->
			<% else %>
				<li>
					<%= link_to " Home", top_path, class: "glyphicon glyphicon-home", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " About", about_path, class: "glyphicon glyphicon-link", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit", "aria-hidden" => true %>
				</li>
				<li>
					<%= link_to " Log in", new_user_session_path, class: "glyphicon glyphicon-log-in", "aria-hidden" => true %>
				</li>
				<% end %>
			</ul>
		</div>

	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<!-- ヘッダーの表示 -->
  	<%= render 'layouts/header' %>

    <div class="container">

      <!-- flashメッセージを表示 -->
      <% if flash[:log_in] %>
        <div class="alert alert-success">
          <%= flash[:log_in] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <!-- フッターの表示 -->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_erorr-messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" id="error_explanation">
    <!-- エラーの件数を表示 -->
    <p><strong><%= object.errors.count %>件のエラーが発生しました。</strong></p>
    <ul>
      <!-- エラーの全文表示 -->
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pages/about.html.erb
<h1>welcome to <span class="glyphicon glyphicon-book" area-hiden="true"></span>Bookers   !!</h1>

app/views/pages/top.html.erb
	<div class="row">

	<div class="col-md-6 col-md-offset-3">
		<h1>welcome to <span class="glyphicon glyphicon-book" area-hiden="true"></span>Bookers   !!</h1>

	<div class="top-text-box">
		<p>
			In <span class="glyphicon glyphicon-book" area-hiden="true"><strong>Bookers</strong></span>,<br>
			you can share and exchange your opinions , inpressions , and emotions
			about varioius books!
		</p>
		<!-- ボタンのグループ -->
		<div class="raw">
			<div class="col-md-10 col-md-offset-1 ">
				<%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block top-btn" %>
				<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block top-btn" %>
			</div>
		</div>
	</div>
		</div>
	</div>

app/views/users/_user-info.html.erb
<h3 class="user-headline">User info</h3>
<% if flash[:user_update] %>
	<div class="alert alert-success">
		<%= flash[:user_update] %>
	</div>
<% end %>
<!-- プロフィール画像 -->
<%= user_image_tag(user, 100, 100, "img-circle center-block") %>

<table class="table">
	<tbody>
		<!-- ユーザーネーム -->
		<tr>
			<th>Name</th>
			<th> <%= user.name %> </th>
		</tr>
		<!-- 紹介文 -->
		<tr>
			<th>Introduction</th>
			<th><%= user.introduction %> </th>
		</tr>
	</tbody>
</table>

<!-- ユーザー情報の編集 -->
<% if user == current_user %>
	<%= link_to "", edit_user_path(user) ,class: "btn btn-default btn-block glyphicon glyphicon-wrench" %>
<% else %>
	<%= link_to "メッセージを送る", user_direct_messages_path(user_id: user.id), class: "btn btn-default btn-block" %>
<% end %>

app/views/users/_user-list.html.erb
<h1><strong>Users</strong></h1>
<!-- 投稿一覧 -->
<table class="table table-hover">
	<thead>
		<tr>
			<th><strong>Image</strong></th>
			<th><strong>Name</strong></th>
		</tr>
	</thead>
	<% users.each do |user| %>
	<tr>
		<!-- プロフィール画像 -->
		<td>
			<%= link_to user_path(user.id) do %>
				<%= user_image_tag(user, 60, 60, "img-circle pull-left") %>
			<% end %>
		</td>
		<!-- ユーザーの名前 -->
		<td><%= user.name %></td>
		<!-- 詳細ページへ -->
		<td class="btn-group">
			<%= link_to "Show", user_path(user), class: "btn btn-info" %>
		</td>
	</tr>
	<% end %>
</table>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'pages/erorr-messages', object: @user %>
			<%= form_for(@user) do |f| %>
				<!-- 名前 -->
				<div class="form-group">
					<%= f.label :name, "名前" %>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				<!-- 自己紹介 -->
				<div class="form-group">
					<%= f.label :introduction, "自己紹介" %>
					<%= f.text_area :introduction, rows: 5, class: "form-control" %>
				</div>
				<!-- プロフィール画像 -->
				<div class="form-group">
					<%= f.label :profile_image, "プロフィール画像" %>
					<%= f.attachment_field :profile_image %>
				</div>

				<%= f.submit "Update User", class: "btn btn-info btn-block" %>

			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-md-3">
		<!-- ユーザー情報 -->
		<%= render 'users/user-info', user: @user %>
		<!-- 新規投稿フォーム -->
		<h4 class="new-book-headline">New book</h4>
		<%= render 'books/book-form', book: @book, btn_name: "Create Book" %>
	</div>

	<div class="col-md-9">
		<!-- 一覧 -->
		<%= render 'users/user-list', users: @users %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<!-- ユーザー情報 -->
		<%= render 'users/user-info', user: @user %>
		<!-- 新規投稿フォーム -->
		<h4 class="new-book-headline">New book</h4>
		<%= render 'books/book-form', book: @book, btn_name: "Create Book" %>
	</div>

	<div class="col-md-9">
		<!-- 投稿一覧 -->
		<%= render 'books/book-list', books: @books %>
	</div>
</div>